version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: customer-service-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: ChatbotAI
    volumes:
      - mongodb_data:/data/db
    networks:
      - customer-service-network

  mongo-express:
    image: mongo-express:latest
    container_name: customer-service-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    depends_on:
      - mongodb
    networks:
      - customer-service-network

volumes:
  mongodb_data:

networks:
  customer-service-network:
    driver: bridge
